import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter/foundation.dart'; // For kIsWeb
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'screens/role_selection_screen.dart';
import 'screens/login_screen.dart';

import 'screens/scan_screen.dart';
import 'screens/valuation_screen.dart';
import 'screens/wallet_screen.dart';
import 'screens/logistics_screen.dart';
import 'screens/success_screen.dart';
import 'screens/map_screen.dart';
import 'screens/active_deal_screen.dart';
import 'screens/main_layout.dart';
import 'screens/recycler_profile_screen.dart';
import 'screens/impact_profile_screen.dart';
import 'screens/marketplace_screen.dart';
import 'screens/transaction_history_screen.dart';
import 'screens/profile_form_screen.dart';
import 'screens/recycler_login_screen.dart';
import 'screens/recycler_dashboard_screen.dart';
import 'screens/recycler_profile_form_screen.dart';
import 'screens/recycler_transaction_scan_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: ".env");

  try {
    // If you haven't generated firebase_options.dart, you can run: flutterfire configure
    // For now, we'll try to initialize, but catch errors to prevent the white screen.
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    if (kDebugMode) {
        print("Firebase initialization failed: $e");
    }
    // You might want to show a friendly error screen here if Firebase helps your app run.
    // For web without options, this will likely fail.
  }

  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
    ),
  );
  runApp(const ReMineApp());
}

class ReMineApp extends StatelessWidget {
  const ReMineApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Re-Mine AI',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF2ECC71),
          brightness: Brightness.light,
        ),
        textTheme: GoogleFonts.interTextTheme(),
        scaffoldBackgroundColor: Colors.white,
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          elevation: 0,
          scrolledUnderElevation: 0,
        ),
      ),
      initialRoute: '/',
      routes: {
        '/':          (context) => const RoleSelectionScreen(),
        '/login':     (context) => const LoginScreen(),
        '/home':      (context) => const MainLayout(), // Pointing /home to MainLayout now
        '/scan':      (context) => const ScanScreen(),
        '/valuation': (context) => const ValuationScreen(),
        '/wallet':    (context) => const WalletScreen(),
        '/logistics': (context) => const LogisticsScreen(),
        '/success':        (context) => const SuccessScreen(),
        '/map':            (context) => const MapScreen(),
        '/active-deal':    (context) => const ActiveDealScreen(),
        '/recycler-profile': (context) => const RecyclerProfileScreen(),
        '/impact-profile': (context) => const ImpactProfileScreen(),
        '/marketplace':    (context) => const MarketplaceScreen(),
        '/transactions':   (context) => const TransactionHistoryScreen(),
        '/profile/edit':  (context) => const ProfileFormScreen(),
        '/recycler-login': (context) => const RecyclerLoginScreen(),
        '/recycler-dashboard': (context) => const RecyclerDashboardScreen(),
        '/recycler-profile-form': (context) => const RecyclerProfileFormScreen(),
        '/recycler/scan-transaction': (context) => const RecyclerTransactionScanScreen(),
      },
    );
  }
}
